server:
 port: 8980
spring: 
 application:
    name: statisticsDaaS
 jpa:
  hibernate:
   ddl-auto: create-drop
   
---
spring:
  profiles: postgres
  datasource:
   url: jdbc:postgresql://localhost:5432/postgres
   username: user
   password: user
   driver-class-name: org.postgresql.Driver